#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# shellcheck disable=SC2016
function run-iptsd-find-service() {
	local -r script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

	source "${script_dir}/iptsd-foreach"

	spdlog warn "iptsd-find-service is deprecated, please use iptsd-systemd"
	run-iptsd-foreach -t touchscreen -i 0 -- echo 'iptsd@$(systemd-escape --path "{}").service'
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
	run-iptsd-find-service "$@"
fi
