#!/bin/sh

check_hid_name() {
	grep -E "^HID_NAME=$2$" "$1/device/uevent"
}

check_ipts() {
	check_hid_name "$1" 'IPTS [A-F0-9]{4}:[A-F0-9]{4}'
}

check_ithc() {
	check_hid_name "$1" 'Intel Touch Host Controller'
}

check_spihid() {
	check_hid_name "$1" 'spi [A-F0-9]{4}:[A-F0-9]{4}'
}

check_uevent() {
	check_ipts "$1" || check_ithc "$1" || check_spihid "$1"
}

find_devices() {
	DEVICES="$(find '/sys/class/hidraw' -mindepth 1 -maxdepth 1)"

	for dev in $DEVICES; do
		check_uevent "$dev" && echo "$dev"
	done
}

HIDRAW="$(find_devices | tail -n1 | grep -Eo "hidraw[0-9]+")"

if [ "$HIDRAW" = "" ]; then
	exit 1
fi

echo "/dev/$HIDRAW"
