/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef _IPTSD_DAEMON_CONSTANTS_HPP_
#define _IPTSD_DAEMON_CONSTANTS_HPP_

#define CONE_COS_THRESHOLD	0.8660 // cos(30 degrees)
#define CONE_DISTANCE_THRESHOLD 1600
#define IPTSD_MAX_STYLI		10

#endif /* _IPTSD_DAEMON_CONSTANTS_HPP_ */
