// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef IPTSD_CONTACTS_DETECTION_ALGORITHMS_OPTIMIZED_CONVOLUTION_HPP
#define IPTSD_CONTACTS_DETECTION_ALGORITHMS_OPTIMIZED_CONVOLUTION_HPP

#include "convolution.3x3-extend.hpp"
#include "convolution.5x5-extend.hpp"

#endif // IPTSD_CONTACTS_DETECTION_ALGORITHMS_OPTIMIZED_CONVOLUTION_HPP
